import type { GymNotification, Promotion, Workout } from './types';

export const workouts: Workout[] = [
  {
    id: 'a',
    day: 'SEG',
    title: 'Treino A',
    subtitle: 'Pernas e glúteos',
    duration: 52,
    level: 'Intermediário',
    accent: 'linear-gradient(135deg, #bd151a 0%, #6b090c 100%)',
    exercises: [
      {
        id: 'squat',
        name: 'Agachamento livre',
        muscle: 'Quadríceps e glúteos',
        sets: 4,
        reps: '10–12',
        rest: '75s',
        video: '/videos/squat-demo.mp4',
        tips: ['Mantenha o peito aberto', 'Joelhos alinhados com os pés', 'Desça de forma controlada'],
      },
      {
        id: 'legpress',
        name: 'Leg press 45°',
        muscle: 'Quadríceps',
        sets: 4,
        reps: '12',
        rest: '70s',
        video: '/videos/squat-demo.mp4',
        tips: ['Não trave os joelhos', 'Mantenha a lombar apoiada', 'Controle a descida'],
      },
      {
        id: 'stiff',
        name: 'Stiff com halteres',
        muscle: 'Posterior de coxa',
        sets: 3,
        reps: '12',
        rest: '60s',
        video: '/videos/curl-demo.mp4',
        tips: ['Quadril para trás', 'Coluna neutra', 'Halteres próximos ao corpo'],
      },
      {
        id: 'calf',
        name: 'Panturrilha em pé',
        muscle: 'Panturrilhas',
        sets: 4,
        reps: '15–20',
        rest: '45s',
        video: '/videos/curl-demo.mp4',
        tips: ['Suba até o máximo', 'Pause no topo', 'Evite impulso'],
      },
    ],
  },
  {
    id: 'b',
    day: 'TER',
    title: 'Treino B',
    subtitle: 'Peito, ombros e tríceps',
    duration: 48,
    level: 'Intermediário',
    accent: 'linear-gradient(135deg, #bd151a 0%, #6b090c 100%)',
    exercises: [
      {
        id: 'bench',
        name: 'Supino reto',
        muscle: 'Peitoral',
        sets: 4,
        reps: '8–10',
        rest: '90s',
        video: '/videos/bench-demo.mp4',
        tips: ['Escápulas encaixadas', 'Pés firmes no chão', 'Barra na linha do peito'],
      },
      {
        id: 'incline',
        name: 'Supino inclinado',
        muscle: 'Peitoral superior',
        sets: 3,
        reps: '10–12',
        rest: '75s',
        video: '/videos/bench-demo.mp4',
        tips: ['Banco entre 30° e 45°', 'Punhos firmes', 'Movimento simétrico'],
      },
      {
        id: 'shoulder',
        name: 'Desenvolvimento',
        muscle: 'Ombros',
        sets: 3,
        reps: '10',
        rest: '70s',
        video: '/videos/bench-demo.mp4',
        tips: ['Abdômen firme', 'Não arqueie a lombar', 'Cotovelo abaixo do punho'],
      },
      {
        id: 'triceps',
        name: 'Tríceps na polia',
        muscle: 'Tríceps',
        sets: 3,
        reps: '12–15',
        rest: '55s',
        video: '/videos/curl-demo.mp4',
        tips: ['Cotovelo junto ao corpo', 'Estenda por completo', 'Sem balançar o tronco'],
      },
    ],
  },
  {
    id: 'c',
    day: 'QUI',
    title: 'Treino C',
    subtitle: 'Costas e bíceps',
    duration: 50,
    level: 'Intermediário',
    accent: 'linear-gradient(135deg, #bd151a 0%, #6b090c 100%)',
    exercises: [
      {
        id: 'pulldown',
        name: 'Puxada frontal',
        muscle: 'Dorsais',
        sets: 4,
        reps: '10–12',
        rest: '75s',
        video: '/videos/pulldown-demo.mp4',
        tips: ['Puxe com os cotovelos', 'Peito levemente elevado', 'Evite jogar o tronco para trás'],
      },
      {
        id: 'row',
        name: 'Remada baixa',
        muscle: 'Costas',
        sets: 4,
        reps: '12',
        rest: '70s',
        video: '/videos/pulldown-demo.mp4',
        tips: ['Coluna neutra', 'Contraia as escápulas', 'Retorne devagar'],
      },
      {
        id: 'curl',
        name: 'Rosca direta',
        muscle: 'Bíceps',
        sets: 3,
        reps: '10–12',
        rest: '60s',
        video: '/videos/curl-demo.mp4',
        tips: ['Cotovelo fixo', 'Sem impulso', 'Contraia no topo'],
      },
      {
        id: 'hammer',
        name: 'Rosca martelo',
        muscle: 'Bíceps e antebraço',
        sets: 3,
        reps: '12',
        rest: '55s',
        video: '/videos/curl-demo.mp4',
        tips: ['Pegada neutra', 'Punhos alinhados', 'Movimento controlado'],
      },
    ],
  },
  {
    id: 'd',
    day: 'SEX',
    title: 'Treino D',
    subtitle: 'Full body e condicionamento',
    duration: 42,
    level: 'Moderado',
    accent: 'linear-gradient(135deg, #bd151a 0%, #6b090c 100%)',
    exercises: [
      {
        id: 'goblet',
        name: 'Agachamento goblet',
        muscle: 'Pernas e core',
        sets: 3,
        reps: '12',
        rest: '60s',
        video: '/videos/squat-demo.mp4',
        tips: ['Halter junto ao peito', 'Pés firmes', 'Core ativado'],
      },
      {
        id: 'pushup',
        name: 'Flexão de braços',
        muscle: 'Peito e tríceps',
        sets: 3,
        reps: 'Máximo técnico',
        rest: '60s',
        video: '/videos/bench-demo.mp4',
        tips: ['Corpo alinhado', 'Cotovelo a 45°', 'Peito próximo ao chão'],
      },
      {
        id: 'row2',
        name: 'Remada unilateral',
        muscle: 'Costas',
        sets: 3,
        reps: '12 cada',
        rest: '60s',
        video: '/videos/pulldown-demo.mp4',
        tips: ['Quadril estável', 'Puxe para o quadril', 'Alongue na descida'],
      },
      {
        id: 'curl2',
        name: 'Rosca alternada',
        muscle: 'Bíceps',
        sets: 3,
        reps: '12 cada',
        rest: '50s',
        video: '/videos/curl-demo.mp4',
        tips: ['Sem girar o tronco', 'Cotovelo junto ao corpo', 'Controle cada repetição'],
      },
    ],
  },
];

export const initialNotifications: GymNotification[] = [
  {
    id: 'n1',
    title: 'Seu treino foi atualizado',
    body: 'A professora Camila ajustou as cargas do Treino A para esta semana.',
    time: 'Há 20 min',
    category: 'treino',
    read: false,
  },
  {
    id: 'n2',
    title: 'Aula especial de funcional',
    body: 'Neste sábado, às 9h. Vagas limitadas e inscrição gratuita na recepção.',
    time: 'Há 2 h',
    category: 'academia',
    read: false,
  },
  {
    id: 'n3',
    title: 'Mensalidade confirmada',
    body: 'Pagamento do plano Premium recebido com sucesso.',
    time: 'Ontem',
    category: 'pagamento',
    read: true,
  },
  {
    id: 'n4',
    title: 'Cupom de suplemento liberado',
    body: 'Use FIT20 e ganhe 20% de desconto em produtos selecionados.',
    time: '2 dias',
    category: 'promo',
    read: true,
  },
];

export const promotions: Promotion[] = [
  {
    id: 'p1',
    kind: 'supplement',
    title: 'Whey Protein 900g',
    description: 'Sabores chocolate e baunilha. Retirada na recepção.',
    badge: '20% OFF',
    oldPrice: 'R$ 149,90',
    price: 'R$ 119,90',
    coupon: 'FIT20',
    endDate: 'Até 20/07',
    image: '/Whey.jpg',
  },
  {
    id: 'p2',
    kind: 'supplement',
    title: 'Creatina 300g',
    description: 'Produto selecionado pela equipe Fit House.',
    badge: 'OFERTA',
    oldPrice: 'R$ 99,90',
    price: 'R$ 79,90',
    coupon: 'CREATINA',
    endDate: 'Até 25/07',
    image: '/Creatina.jpg',
  },
  {
    id: 'p3',
    kind: 'raffle',
    title: 'Sorteio Kit Performance',
    description: 'Concorra a mochila, coqueteleira, camiseta e um mês de academia.',
    badge: 'SORTEIO',
    endDate: 'Resultado em 31/07',
  },
];
